
version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-s3: circleci/aws-s3@2.0

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows

jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install dependencies in both apps
      - run:
          name: Install pip
          command: |
            sudo apt update
            sudo apt install -y python3-pip python3-dev
      - run:
          name: Install AWS dependencies
          command: |
            sudo pip install awsebcli
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Back-End Test
          command: |
            npm run backend:test
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
